### ISSUE TITLE
Disable infinite looping

### ISSUE THREAD

**Issue by pieterclaerhout** [KyoheiG3/PagingView#1]
Hi,

Is there a way to disable the infinite looping?

Kind regards,

Pieter

**Comment by KyoheiG3** [comment]
Hi, @pieterclaerhout 

Impossible to disable.
You need?

**Comment by pieterclaerhout** [comment]
Actually, yes, I would need it...

Thanks,

Pieter

**Comment by KyoheiG3** [comment]
@pieterclaerhout 

Infinite looping disable flag was added in [0.3.0](https://github.com/KyoheiG3/PagingView/tree/0.3.0).
