### ISSUE TITLE
Better reloadData()

### ISSUE THREAD

**Issue by rad182** [KyoheiG3/PagingView#4]
Hi. I'm having an issue with reloadData() because it's resetting the scrollview back to the first indexPath. What i'm expecting for reloadData() is the same with tableView/collectionView that it will stay at the current indexPath and just reload the other visible cells. Is this possible? TIA

**Comment by KyoheiG3** [comment]
Hi @rad182 

```
optional func indexPathOfStartingInPagingView(pagingView: PagingView.PagingView) -> NSIndexPath?
```

https://github.com/KyoheiG3/PagingView#pagingviewdatasource-function

This function will be called, after reload. Please return the `NSIndexPath` before reload if needed.

**Comment by rad182** [comment]
that worked! thanks @KyoheiG3 . But shouldn't be the framework will handle the starting/current index path?

**Comment by KyoheiG3** [comment]
It was done so. However, i have been changed by [this issue](https://github.com/KyoheiG3/PagingView/pull/3).

When `numberOfItems` has been changed, can’t help it.

**Comment by rad182** [comment]
ah okay. thanks @KyoheiG3 ! awesome framework

**Comment by KyoheiG3** [comment]
Tanks @rad182
