### ISSUE TITLE
Infinite Loop with one or two images.

### ISSUE THREAD

**Issue by diegoalex** [KyoheiG3/PagingView#9]
When you have only one or two images and the infinite loop is set to true, it's showing only one image and bug when you swipe right. (with more than 2 images work fine)

**Comment by wrlqwe** [comment]
I have fix it by replacing 0..<min(Position.count, allItemCount) to 0..<Position.count in source code

**Comment by KyoheiG3** [comment]
Fixed in https://github.com/KyoheiG3/PagingView/pull/11. Thanks.
